### ISSUE TITLE
Falsy check on payload leads to payloadError when using first element of an enum

### ISSUE THREAD

**Issue by stijn26** [Infinium8/useUndoable#16]
Hi,

When using the mutate function with an enum, a payloadError is throwed because payload is evaluated to false, because the first element in an enum evaluates to 0.

For now we use a PLACEHOLDER value in our enum to work around the issue.

```
var mutate = function mutate(state, action) {
  var past = state.past,
      present = state.present,
      future = state.future;
  var payload = action.payload,
      behavior = action.behavior,
      historyLimit = action.historyLimit,
      ignoreIdenticalMutations = action.ignoreIdenticalMutations,
      cloneState = action.cloneState,
      ignoreAction = action.ignoreAction;

  if (!payload) { // this line is the culprit
    payloadError('mutate');
  }
```

**Comment by xplato** [comment]
Hello!

Thanks for bringing this up. Could you provide a little more information on your use case?

What does the enum look like? What does your usage of the hook look like? I'm trying to synthesize a solution that will work correctly, as this condition could potentially cause some backward compatibility issues.

**Comment by xplato** [comment]
Hey @stijn26, quick ping here :)

**Comment by xplato** [comment]
I'm going to close this due to inactivity. If you decide to revisit it, I will reopen this.
