### ISSUE TITLE
Version 5.0.0 on NPM

### ISSUE THREAD

**Issue by KPJ-93** [Infinium8/useUndoable#29]
No hurry, but I was wondering if you looked into updating NPM with the new version 5.0.0.

Was not entirely sure if I should ask in the latest closed PR or here (since technically there were commits after it)

Thanks!

**Comment by xplato** [comment]
Hey @KPJ-93! Thank you for your patience. I had to fix a few internal type issues before I could publish it (with a clean conscience, that is 😅). With that said, v5.0.0 has been published on NPM now. Thank you!
