### ISSUE TITLE
Issue when doing undo/someactions/ and undo again

### ISSUE THREAD

**Issue by vallsv** [Infinium8/useUndoable#31]
Hi,

I have recently played with your library.

I found out that it is very convenient, but i feel like it is not working well with the history when you use multiple time undo.

Or maybe i misunderstand the history.

I you apply the following chages
```
A B C [D] <- current state
```
Then undo to B
```
A [B] C D
```
At this stage you can "redo" to go to `C` then `D` but if you do a new action `C` and `D` should disappear
```
A B [C2]
```

I feel like it does not behave at all this way.

I just read the documentation, what i am searching for is what you call `destroyFuture`?

Thanks a lot in advance.

**Comment by xplato** [comment]
Hey @vallsv, if I'm understanding correctly, I think `destroyFuture` is precisely the mutation behavior you're looking for.

Here's a quick demonstration of that behavior:

https://github.com/xplato/useUndoable/assets/87919558/9e646624-6d3f-4ee0-b103-78e6d6326402

Note that you can set this on the hook globally using the options, or on a case-by-case basis which each call to `setState`:

```js
const [state, setState] = useUndoable(0, {
  mutationBehavior: "destroyFuture"
})

setState(1, "destroyFuture")
```

---

Let me know if that works for you!

**Comment by vallsv** [comment]
Very nice. This works perfectly.
Thanks for your feedback.
