### ISSUE TITLE
Helper for live interaction

### ISSUE THREAD

**Issue by vallsv** [Infinium8/useUndoable#32]
Hi,

I am working on complex interaction with multiple components supporting drag and drop.

I found out that it was much easier to handle that by wrapping your hook inside and own code, allowing me to handle a "live" state which is not yet part of the history.

For example during a mouse drag, all my components are aware of the new state, but this state is not yet part of the history.
At the end of the mouse interaction it be came part of the history.

I call it "intermediate" state.

Would you be interested in such behavior, or by chance is there a way to setup your hook to behave this way?

Here is my actual code:

```
import { useMemo, useState } from 'react';
import useUndoable from 'use-undoable';

/**
 * A useUndoable hook featuring an intermediate present state
 * which is not yet archived in the history.
 *
 * This simplifies a lot interaction between multiple components.
 */
export default function useUndoableWithIntermediate<T>(props: T): [
  T,
  (state: Partial<T>, intermediate?: boolean) => void,
  {
    past: T[];
    future: T[];
    undo: () => void;
    canUndo: boolean;
    redo: () => void;
    canRedo: boolean;
    reset: (initialState?: T) => void;
    resetInitialState: (newInitialState: T) => void;
  }
] {
  const [present, setPresent, actions] = useUndoable<T>(props);
  const [intermediate, setIntermediate] = useState<Partial<T> | undefined>(
    undefined
  );

  const state = useMemo(() => {
    return { ...present, ...intermediate };
  }, [present, intermediate]);

  function setState(value: Partial<T>, intermediate?: boolean) {
    if (intermediate) {
      setIntermediate((state) => {
        return { ...state, ...value };
      });
    } else {
      setPresent((state: T) => {
        return { ...state, ...value };
      });
      setIntermediate(() => undefined);
    }
  }

  return [state, setState, actions];
}
```

And I use it this way:
```
# During the drag interaction
setState(newState, true);
# At the end of the drag
setState(newState, false);
```

It works pretty well.

**Comment by xplato** [comment]
Hey @vallsv, I like this solution! I'm wondering if this achieves the same effect as the `ignoreAction` param on `setState`, however. Take a look at this [crude example I whipped up in CodeSandbox.](https://codesandbox.io/p/sandbox/useundoable-drag-sdkdl5?file=%2Fsrc%2FExample.tsx%3A1%2C1-88%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv2lp8vl00063d5u88i6mubi%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv2lp8vl00023d5u1llezszi%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv2lp8vl00033d5uy79o1sl8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv2lp8vl00053d5usn7ndxro%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv2lp8vl00023d5u1llezszi%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv2lp8vk00013d5utaraf0la%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clv2m9tqq00023d5u2fhphoyq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A88%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FExample.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clv2lp8vl00023d5u1llezszi%2522%252C%2522activeTabId%2522%253A%2522clv2m9tqq00023d5u2fhphoyq%2522%257D%252C%2522clv2lp8vl00053d5usn7ndxro%2522%253A%257B%2522id%2522%253A%2522clv2lp8vl00053d5usn7ndxro%2522%252C%2522activeTabId%2522%253A%2522clv2mhmpn001e3d5uyiczu6rf%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clv2mhmpn001e3d5uyiczu6rf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clv2lp8vl00033d5uy79o1sl8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clv2lp8vl00033d5uy79o1sl8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

The whole state is tracked via useUndoable here. Every time `onMouseMove` is called, it'll call `setPosition` with the final param, `ignoreAction`, set to `true`—this way, it'll only update the `present` state. However, 300 milliseconds after you stop moving the mouse, `setPosition` is called normally, and the state is updated as you'd expect.

It's a crude and not-very-performant example, but it demonstrates how events with a huge quantity of calls can be handled without polluting the state.

Does this generally fit your requirement or is there something else I'm not considering that your `useUndoableWithIntermediate` hook covers?

Thanks for opening an issue, by the way! 😄

**Comment by vallsv** [comment]
Thanks for your feedback. Sounds like the same use case.

I unfortunately don't have much time to play with it now , But ill go back to this task in couple of months.

Feel free to close this issue if you prefer, i could reopen it in case.

**Comment by xplato** [comment]
No worries! Feel free to reopen it when you get back to it :)
