### ISSUE TITLE
Undo Redo In React-flow

### ISSUE THREAD

**Issue by Hamza-malikx** [Infinium8/useUndoable#8]
Hey, greeting !
Firstly, thank u for your contributions to react-flow but right now the issue I am facing is that when I use custom nodes and edges and I have initial nodes as empty then undo-redo doesn't work for me. Could u guys plss help me with it.

**Comment by xplato** [comment]
Can you share some of your code with me so I can have some context?

When you call `useUndoable()` the value inside the parentheses is your initial state. If you have it as an empty array by default, it stands to reason it will always be empty unless you manually add items to the state.

**Comment by Hamza-malikx** [comment]
Ok,, I will probably be sharing a video with you in a day or so and if you could help me that would means a-lot. Meanwhile, we are fixing some other issues in our project. 
Thank u for giving me your precious time :)

**Comment by xplato** [comment]
I'm going to close this due to inactivity, but feel free to re-open it when/if you'd like to revisit this. Thanks!
