### ISSUE TITLE
Passing ignoreAction parameter causes ts(2554) error

### ISSUE THREAD

**Issue by rfdearborn** [Infinium8/useUndoable#9]
Great package! 

When passing `ignoreAction` to `setState`, typescript shows `Expected 1-2 arguments, but got 3. ts(2554)`. Looks like `ignoreAction?: boolean` should be added [here](https://github.com/Infinium8/useUndoable/blob/e01ed3815c07dcf7497a6ee51b84f6ddf892c1f5/src/useUndoable.ts#L27)? I'm on 3.3.10.

**Comment by xplato** [comment]
Nice catch! Version [`3.3.11`](https://github.com/Infinium8/useUndoable/commit/7ae9becc9129f0f11b823b3c01413b87542eb36f) should resolve this issue.

Thank you for the heads up!
